-- Slotopol storage baseline for PostgreSQL.
-- This migration is intentionally explicit; runtime xorm.Sync remains for dev/demo
-- while production should apply SQL migrations before application startup.

BEGIN;

CREATE TABLE IF NOT EXISTS schema_migrations (
    version TEXT PRIMARY KEY,
    applied_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS club (
    cid BIGSERIAL PRIMARY KEY,
    ctime TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    utime TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    name TEXT NOT NULL,
    bank DOUBLE PRECISION NOT NULL DEFAULT 0,
    fund DOUBLE PRECISION NOT NULL DEFAULT 0,
    lock DOUBLE PRECISION NOT NULL DEFAULT 0,
    rate DOUBLE PRECISION NOT NULL DEFAULT 2.5,
    mrtp DOUBLE PRECISION NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS "user" (
    uid BIGSERIAL PRIMARY KEY,
    ctime TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    utime TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    email TEXT NOT NULL UNIQUE,
    secret TEXT NOT NULL,
    name TEXT NOT NULL,
    code BIGINT NOT NULL DEFAULT 0,
    status BIGINT NOT NULL DEFAULT 0,
    gal BIGINT NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS props (
    cid BIGINT NOT NULL,
    uid BIGINT NOT NULL,
    ctime TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    utime TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    wallet DOUBLE PRECISION NOT NULL DEFAULT 0,
    access BIGINT NOT NULL DEFAULT 0,
    mrtp DOUBLE PRECISION NOT NULL DEFAULT 0,
    PRIMARY KEY (cid, uid),
    FOREIGN KEY (cid) REFERENCES club(cid) ON DELETE CASCADE,
    FOREIGN KEY (uid) REFERENCES "user"(uid) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS story (
    gid BIGINT PRIMARY KEY,
    cid BIGINT NOT NULL,
    uid BIGINT NOT NULL,
    alias TEXT NOT NULL,
    ctime TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    closed BOOLEAN NOT NULL DEFAULT FALSE,
    xtime TIMESTAMPTZ,
    FOREIGN KEY (cid) REFERENCES club(cid) ON DELETE CASCADE,
    FOREIGN KEY (uid) REFERENCES "user"(uid) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS wallet_ledger (
    id BIGSERIAL PRIMARY KEY,
    cid BIGINT NOT NULL,
    uid BIGINT NOT NULL,
    actor_uid BIGINT NOT NULL DEFAULT 0,
    gid BIGINT NOT NULL DEFAULT 0,
    sid BIGINT NOT NULL DEFAULT 0,
    ctime TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    balance_type TEXT NOT NULL DEFAULT 'coins',
    op TEXT NOT NULL,
    amount DOUBLE PRECISION NOT NULL,
    balance_before DOUBLE PRECISION NOT NULL,
    balance_after DOUBLE PRECISION NOT NULL,
    meta TEXT,
    FOREIGN KEY (cid) REFERENCES club(cid) ON DELETE CASCADE,
    FOREIGN KEY (uid) REFERENCES "user"(uid) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS walletlog (
    id BIGSERIAL PRIMARY KEY,
    cid BIGINT NOT NULL,
    uid BIGINT NOT NULL,
    aid BIGINT NOT NULL,
    ctime TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    wallet DOUBLE PRECISION NOT NULL,
    sum DOUBLE PRECISION NOT NULL
);

CREATE TABLE IF NOT EXISTS banklog (
    id BIGSERIAL PRIMARY KEY,
    ctime TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    bank DOUBLE PRECISION NOT NULL,
    fund DOUBLE PRECISION NOT NULL,
    lock DOUBLE PRECISION NOT NULL,
    banksum DOUBLE PRECISION NOT NULL,
    fundsum DOUBLE PRECISION NOT NULL,
    locksum DOUBLE PRECISION NOT NULL
);

CREATE TABLE IF NOT EXISTS spinlog (
    sid BIGINT PRIMARY KEY,
    gid BIGINT NOT NULL,
    ctime TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    mrtp DOUBLE PRECISION NOT NULL,
    game TEXT NOT NULL,
    wins TEXT,
    gain DOUBLE PRECISION NOT NULL,
    wallet DOUBLE PRECISION NOT NULL
);

CREATE TABLE IF NOT EXISTS multlog (
    id BIGINT PRIMARY KEY,
    gid BIGINT NOT NULL,
    ctime TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    mrtp DOUBLE PRECISION NOT NULL,
    mult DOUBLE PRECISION NOT NULL,
    risk DOUBLE PRECISION NOT NULL,
    win BOOLEAN NOT NULL,
    gain DOUBLE PRECISION NOT NULL,
    wallet DOUBLE PRECISION NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_props_uid ON props(uid);
CREATE INDEX IF NOT EXISTS idx_story_uid ON story(uid);
CREATE INDEX IF NOT EXISTS idx_story_cid ON story(cid);
CREATE INDEX IF NOT EXISTS idx_story_closed_xtime ON story(closed, xtime);
CREATE INDEX IF NOT EXISTS idx_wallet_ledger_uid_cid ON wallet_ledger(uid, cid);
CREATE INDEX IF NOT EXISTS idx_wallet_ledger_gid ON wallet_ledger(gid);
CREATE INDEX IF NOT EXISTS idx_wallet_ledger_sid ON wallet_ledger(sid);
CREATE INDEX IF NOT EXISTS idx_wallet_ledger_op ON wallet_ledger(op);
CREATE INDEX IF NOT EXISTS idx_wallet_ledger_balance_type ON wallet_ledger(balance_type);
CREATE INDEX IF NOT EXISTS idx_walletlog_uid_cid ON walletlog(uid, cid);
CREATE INDEX IF NOT EXISTS idx_spinlog_gid ON spinlog(gid);
CREATE INDEX IF NOT EXISTS idx_multlog_gid ON multlog(gid);

INSERT INTO schema_migrations(version)
VALUES ('0001_baseline')
ON CONFLICT (version) DO NOTHING;

COMMIT;
